Repository LoginRadius/go-saml, pull requests merged in 2020-10, with the labels that each got.

#11 implemented Reject struct in idp.go
  idp.go
Labels: in review

#13 Add support for SHA-1 in responses
  idp.go
  internal/authnResponse.go
  internal/logoutResponse.go
  saml.go
Labels: in review

#14 feat: add support to read cert and keys from files
  examples/certs/idp.key
  examples/certs/idp.pem
  examples/certs/sp.pem
  idp.go
  saml.go
Labels: in review

#20 Update README.md
  README.md
Labels: Status: Accepted, hacktoberfest-accepted

#19 Return parsed values of AuthnRequest to get attributes like ForceAuthn
  examples/response.go
  go.mod
  go.sum
  idp.go
  internal/schema.go
  parse.go
  saml.go
Labels: Status: Accepted, hacktoberfest-accepted

#17 Remove unused variables and fields
  internal/schema.go
Labels: Status: Accepted

#26 Running the example leads to SIGNED_XML_ERROR - Unsupported Algorithm
  saml.go
Labels: Status: Accepted, hacktoberfest-accepted

#27 Add Organization and Contact details in the Idp metadata
  examples/metadata.go
  idp.go
  internal/schema.go
  saml.go
Labels: Status: Accepted, hacktoberfest-accepted

#24 Use consistent method receiver names
  internal/logoutRequest.go
Labels: hacktoberfest-accepted
